### ISSUE TITLE
Map export yields blank image when there is no room present in the center of the map

### ISSUE THREAD

**Issue by henck** [henck/trizbort#1]
Supported formats must be PNG, JPG, SVG

**Comment by Happy-Ferret** [comment]
What's the status for this?
The code appears to be in place and the [April 30, 2018 Update](http://www.trizbort.io/castle-of-doom-sample-map.html) references this feature, but when I actually try to save a `.png`, the result is an empty square.

**Comment by henck** [comment]
Interesting. That is a strange requirement for the export to work. The export does work (I've used it a number of times for different maps), but I'll need to look into this.

**Comment by henck** [comment]
I see the problem. The export starts by drawing the center 100x100 of the map onto a canvas. It then scans the pixels as the edges to see if everything fits on the canvas. If not, it enlarges the canvas and export again, until everything fits. This fails when the center of the map is empty, because the export thinks it's done.

The reason for this approach is that it is difficult to calculate where curved connections between rooms may be, and I didn't want them to be cropped off the exported image.

A better approach would be to measure the position of all rooms first and size the canvas do that, then enlarge the canvas until nothing is cropped.

I am very pleased that you found this, because it's a scenario that I never had and didn't realize this would happen.

**Comment by henck** [comment]
I have renamed this issue to reflect the problem. Image export _is_ implemented, but there is a flaw.

**Comment by henck** [comment]
This issue is now fixed. The canvas is first sized to contain all boxviews (rooms, notes, blocks), then drawn several times until all curves are also contained. Map images are now correctly exported.

**Comment by henck** [comment]
Note: this change is now live on trizbort.io.
