### ISSUE TITLE
PWA changes not live on https://trizbort.io/app/index.html

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#107]
https://trizbort.io/app/index.html differs from https://github.com/henck/trizbort/blob/master/index.html in a number of ways, but, most notably, it's missing the changes from PR #79.

* `<link rel="manifest" href="manifest.webmanifest">` is missing.
* Even if it were there, https://trizbort.io/app/manifest.webmanifest is 404
* The `<script type="module">` section is missing.

Once these changes fully deploy, then Trizbort.io could be installed locally as a PWA.

**Comment by djducat** [comment]
is this project still being worked on?  This is a great enhancement that seems pretty straight forward.

**Comment by henck** [comment]
I have deployed the changes now. It seems that Trizbort can now be installed locally; I did see an install option on Chrome.
I apologize for the very long delay.

**Comment by djducat** [comment]
thanks so much for jumping on this!  Just tested it in Safari and it works great.  Installed it as a Mac App and took the laptop offline, and the app still worked offline.  Thanks!
