### ISSUE TITLE
Deploying to local [local resources blocked]

### ISSUE THREAD

**Issue by Selsynn** [henck/trizbort#16]
Hello, I'm not familiar at all with JAMstack, but when I run grunt watch, and I open local index.html, it can't load any ressources. (svg, css, js/ts)
`Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at file:///mnt/myfilePath/trizbort/app. (Reason: CORS request not http).`
1) Is it normal there is no use of jamstack (nothing to install in the dev machine ?)
2) When you said to open index.html, you mean to really open index.html from the  base folder ? Or is there a localhost we could go ? (and if so, at which port ?)

Thanks !

**Comment by henck** [comment]
JAMstack means JavaScript with HTML APIs. There is no server back-end, no database. You'll need to run a webserver to open index.html. Try the Node.js web server, or install Apache locally.

**Comment by Selsynn** [comment]
Ok thanks you ! I will try it !
