### ISSUE TITLE
Pull Requests accepted?

### ISSUE THREAD

**Issue by Happy-Ferret** [henck/trizbort#21]
Curious.

Do you currently accept PRs for Trizbort.io?
I found a couple bugs I fixed/am fixing in my [fork](https://github.com/middangeard-fiction/yggdrasil).

**Comment by Selsynn** [comment]
Last year I was active (and had time) and my PR were accepted in the day I submitted them, so I think you can just submit yours and see what happens, but he should accept it.

**Comment by henck** [comment]
Hello,
Yes, I warmly welcome PRs and will review and accept them. I will also need to build the project and publish the changes to trizbort.io. This may take some time so changes to the published version might not be instant (but I will do my best).

**Comment by Happy-Ferret** [comment]
Thanks!

Just committed my second PR. The first one was already merged moments after I opened it. Superb reaction speed. :+1:
