### ISSUE TITLE
Trizbort importer inoperable beyond first (successful) import

### ISSUE THREAD

**Issue by Happy-Ferret** [henck/trizbort#27]
Here's an odd bug I spotted last weekend and have been unable to resolve thus far.

After successfully importing a Trizbort map for the first time, the Trizbort import option essentially becomes a no-op. The import dialog still pops up but upon confirming the import, nothing happens. No error is being logged either.

Given I call the same ``importMap(text: string)`` method in my desktop app specific implementation, I don't think the method itself is where the issue originates from.

It remotely feels as if the ``inputImport`` event listener is silently removed, but I cannot figure out why that would be the case. No such issue arises with ``inputLoad``.

**Comment by henck** [comment]
I've just tried this:
- Import a .trizbort map (successful)
- New map (map is cleared)
- Import a .trizbort map (successful)
- Import a .trizbort map (successful - map is overwritten)

I am not experiencing the same problem. It might be possible that this bug was inadvertently solved when the issue with the Window control was solved? Can you try this with the latest code?

**Comment by Happy-Ferret** [comment]
I just tried it directly from Trizbort.io

Same problem. I open a copy of ``echanter.trizbort`` (taken from the ``samples/`` folder), and this will succeed the first time but not thereafter.

**Comment by Happy-Ferret** [comment]
Hm. That's peculiar. When I alternate between two different .trizbort files, it actually loads both of them properly.

"New map" and re-importing the previous selection fails.
Re-importing the same map without clearing the map editor first also fails.

**Comment by Happy-Ferret** [comment]
Curious. Very curious.

I just tried Firefox. Here it works as advertised.
It appears this is a Chrome specific issue. Something specific to their file dialog? Do they check if a chosen file is unique in relation to a prior invocation of that dialog?

**Comment by henck** [comment]
A user once reported being unable to load maps he previously saved. I closed that issue since because I couldn't reproduce it. The user said they were using Mac + Chrome. This may be related.

**Comment by Happy-Ferret** [comment]
Fine by me.

I'll mark both as resolved in the PR, as soon as I'm ready.
Just testing a few more things.

**Comment by henck** [comment]
Chrome issue now solved.
