### ISSUE TITLE
Remove sample maps from code

### ISSUE THREAD

**Issue by henck** [henck/trizbort#38]
Currently, the sample maps are part of the main code body. They should be moved to separate JSON files and downloaded by Trizbort.io as necessary.

**Comment by henck** [comment]
You can now open `http://trizbort.io?map=http://trizbort.io/maps/adventure.json`, for example.

**Comment by jeremydouglass** [comment]
> You can now open `http://trizbort.io?map=http://trizbort.io/maps/adventure.json`, for example.

Is that link working for you? For me it appears to load the homepage.

**Comment by henck** [comment]
Oops. That link should have been http://trizbort.io/app/?map=http://trizbort.io/app/maps/adventure.json

I've updated my post above, as well.
