### ISSUE TITLE
Big gap in side-bar appears & breaks positioning

### ISSUE THREAD

**Issue by Liquidream** [henck/trizbort#41]
Hi,

I've just stumbled across Trizbort and it's great - I really wanna use it to map out my next game.
However, it seems the current build has an issue where, after opening the properties side-bar pane - an additional "gap" appears.

**CORRECTION**: This only happens if you Double-Click an item (using the ellipse [...] button is ok)

Unfortunately, it's not just aesthetically annoying - as this gap also throws off the mouse position for clicking and using the editor (making it effectively unusable). 😥
(It's fine when it first loads - it only seems to happen after opening the properties pane)

Tested in: **Brave**, **Edge** "Chromium"

![GIF](https://user-images.githubusercontent.com/2211678/77879816-23ff3000-7253-11ea-8076-e2cc8f818bf8.gif)

**Comment by Liquidream** [comment]
Ok, I'm not really a web developer, but I've noticed that if you temporarily disable the `transition` style that the side-panel (`.panel`) uses, that seems to resolve the issue.

While it might be a hack, I'm might just run with it - if it'll let me use the tool for now! 😅

**Comment by jeremydouglass** [comment]
I can confirm

**Comment by jeremydouglass** [comment]
Here are screenshots:

![Screen Shot 2020-05-05 at 3 51 41 PM](https://user-images.githubusercontent.com/798570/81124071-674f5d00-8ee9-11ea-91b9-4b707d292a4c.png)
![Screen Shot 2020-05-05 at 3 51 46 PM](https://user-images.githubusercontent.com/798570/81124079-69b1b700-8ee9-11ea-968e-7a29d4f55076.png)
![Screen Shot 2020-05-05 at 3 52 42 PM](https://user-images.githubusercontent.com/798570/81124088-6dddd480-8ee9-11ea-9f94-5cff80dcbb67.png)

**Comment by jeremydouglass** [comment]
I can confirm that removing css transitions from .panel fixes the problem here.

Those seem to be here:

https://github.com/henck/trizbort/blob/master/styl/panel.styl

I can make a pull request if you like.

**Comment by henck** [comment]
I want to thank both of you (@Liquidream, @jeremydouglass) for your clear feedback and screenshots. I have disabled the panel open/close animation, hoping that this does indeed solve the problem.

**Comment by jeremydouglass** [comment]
Thanks! I just tested it on the live site, and the deployed fix worked in my browser -- the gap no longer appears, no matter how I activate and close menus.
