### ISSUE TITLE
Github link broken

### ISSUE THREAD

**Issue by jeremydouglass** [henck/trizbort#44]
```
https://github.com/henck%2Ftrizbort
```

Your social.html escapes the /, breaking your setting. Needs to be just your username, or drop the escaping from social.html

https://github.com/henck/trizbort/blob/71a2fd535d6569b095cc1417c6de7f2cf7298bd0/site/_config.yml#L26

Really great project, btw. I helped test Informer for OmniGraffle back in the 00s, and have recently been thinking about a project just like this.

**Comment by henck** [comment]
Ah, much better! Thank you!
