### ISSUE TITLE
Backspace should delete a room

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#47]
Create a room, click on it, and press backspace. (On macOS keyboards, this key is labeled "delete," but it's still keyCode 8, not the delete keyCode 46, which you can type by holding the "fn" key while you press "delete".)

Desired: Backspace should delete the selected room

Actual: On Firefox 76 for macOS Catalina 10.15.4, the backspace key navigates back; you see the `beforeunload` popup. (On Chrome 81, nothing happens when you press backspace.)

**Comment by henck** [comment]
Added backspace to keyboard help (see #70)
