### ISSUE TITLE
Undo

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#52]
I wish there were a way to undo changes, e.g. deleting a room.

**Comment by dfabulich** [comment]
D'oh, it's in a keyboard shortcut. And it's specifically "Ctrl-Z", which I didn't expect, because on macOS undo is normally Cmd-Z.

**Comment by jeremydouglass** [comment]
Hmm. I suppose it could be localized based on browser detection. That's what Google Docs does with Ctrl-Z / Cmd-Z.

<img width="516" alt="Screen Shot 2020-05-06 at 10 26 55 AM" src="https://user-images.githubusercontent.com/798570/81208640-3a9c5380-8f84-11ea-90e4-6ba5152dbca1.png">

**Comment by jeremydouglass** [comment]
Ah, you already requested that in #53
