### ISSUE TITLE
On macOS, use Cmd instead of Ctrl for keyboard shortcuts

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#53]
Trizbort has a few "standard" keyboard shortcuts with the Ctrl key:

* Ctrl A: Select All
* Ctrl C: Copy
* Ctrl V: Paste
* Ctrl Z: Undo

On macOS, these keyboard shortcuts are normally bound to the Cmd key ⌘; it would be great if I could use those there instead.

**Comment by henck** [comment]
Added new shortcuts to keyboard help (see #70)
