### ISSUE TITLE
Keyboard shortcuts to select a room

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#54]
Create a room. Use shift-up to create a room to the north.

Actual: The original room is selected. There's no way (that I can see) to use the keyboard to select the room you just created

Desired: At the very least, pressing the tab key should support selecting rooms. It would be nifty if there were a keyboard shortcut (tab + up?) to navigate to the room to the north.

**Comment by dfabulich** [comment]
It would be especially handy to have a keyboard shortcut to select the room that was just created with shift-arrow.

**Comment by jeremydouglass** [comment]
> It would be especially handy to have a keyboard shortcut to select the room that was just created with shift-arrow.

The easiest thing would be to, before creating a room, check if a room exists in that direction. If it does, move to it, if not, create it.

Then the full room-shortcut scheme is also the room-navigation scheme, and you can move around the map with shift-dir -- or make rooms if the aren't there already.

**Comment by dfabulich** [comment]
I like that. There's already a check to to see if the room exists, but right now, if the room does exist, the shortcut does nothing.
