### ISSUE TITLE
HTTPS on trizbort.io

### ISSUE THREAD

**Issue by dfabulich** [henck/trizbort#60]
http://trizbort.io/ doesn't support HTTPS. Chrome, Firefox, and Safari all show a prominent "Not Secure" warning in the URL bar.

**Comment by dfabulich** [comment]
I recommend CloudFlare for this.

**Comment by henck** [comment]
I'm running Trizbort.io on a shared hosting solution that doesn't really seem to offer https. I'll have to look into this.

**Comment by henck** [comment]
It looks like I can in fact get a certificate on my server. I'm fiddling with my host's management tools now.

**Comment by henck** [comment]
I got it working. You can now use https://www.trizbort.io.
